# Change these first
owner: chandr1000 # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: "Chandra's Network Web Service"
    url: https://www.chandr1000.net
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.chandr1000.net
  # baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Status Page"
  introTitle: "Chandra's Network Status Page"
  introMessage: "Kamu saat ini berada di halaman status. Kamu dapat melihat berbagai kendala dan insiden yang terjadi di infrastruktur [Chandra's Network](https://chandr1000.net). Halaman ini diciptakan untuk membantu kamu mengetahui penyebab kendala yang sedang dihadapi Chandra's Network secara **real-time**."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Kembali ke situs asli
      href: https://chandr1000.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
